### PR TITLE
fix travis

### PR DESCRIPTION
**Pull request by massich**
lets see what this does.

### CODE REVIEW

**Comment by massich** [comment]
@hichamjanati 	there you go! Travis is green except for `numpydoc`. Learn how to write damn it!

**Comment by massich** [comment]
Feel free to push in the PR and merge.

**Comment by hichamjanati** [comment]
> @hichamjanati there you go! Travis is green except for `numpydoc`. Learn how to write damn it!

I'm sad and kind of relieved at the same time that it did not take 10 seconds to be solved :)

**Comment by hichamjanati** [comment]
Finally, thanks @massich. Shall we merge ?

**Pull request merged**
